import type { Metadata } from "next";
import localFont from "next/font/local";
import { Oswald, Raleway } from 'next/font/google'
import "./globals.css";

/*const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});*/

const headerFont = Oswald ({
  variable: "--font-oswald",
  subsets: ['latin'],
})

const bodyFont = Raleway ({
  variable: "--font-raleway",
  subsets: ['latin'],
})

/*const bodyFont = localFont({
  src:"/fonts/Raleway.woff",
  variable: "--font-raleway",
  weight: "100 900",
});*/

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${headerFont.variable} ${bodyFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
